version: 0.2
env:
  variables:
    APP_NAME: "facebook-ui-clone"
phases:
  install:
    runtime-versions:
      nodejs: 14.x
    commands:
      - echo install process started
      - npm install && npm install -g @angular/cli
  pre_build:
    commands:
      - echo Testing started now
      - npm run test
  build:
    commands:
      - echo build process started now
      - npm run build
  post_build:
    commands:
      - echo build process finished, we should uplload to S3 now
      - cd dist/$APP_NAME
      - ls -la
      - aws s3 sync . s3://fb-angular-bucket --delete
      - echo upload finished
